# WAN-Analytics-IoT

For instructions on the setup of the devices, please see link:/README-raspberrypi.adoc[README - Raspberry PI]


### Setup Geode

----
$ cd server
$ gfsh

gfsh>  start locator --name=locator1 --mcast-port=0 --bind-address=<ADDRESS>
gfsh> start server --name=server1 --mcast-port=0 --bind-address=<ADDRESS>
gfsh> create region --name=/Probe_requests --type=PARTITION
gfsh> create region --name=/Distances --type=REPLICATE
gfsh> create region --name=/DeviceLocations --type=REPLICATE
gfsh> create region --name=/RaspberryPIs --type=REPLICATE
----

### Setup Spring XD

- Start Spring XD server
----
$ xd-singlenode
(...)
----

- Modify the file server/streams.xd to connect to the right XD server as creating the stream.
- Create the stream:

----
$ xd-shell --cmdfile streams.xd
Jul 15, 2015 11:12:56 PM org.springframework.shell.core.AbstractShell handleExecutionResult
INFO: Successfully targeted http://172.20.14.47:9393
Jul 15, 2015 11:13:07 PM org.springframework.shell.core.AbstractShell handleExecutionResult
INFO: Created and deployed new stream 'input'
----

### Start the GUI

- Modify the file __server/WebConsole/src/main/resources/client.xml__ to connect to the right Gem locator host
- Startup the client:

----
$ cd server/WebConsole
$ ./gradlew run
----

- Open the browser at __http://<server>:8080/


### Start clients 

For each Raspberry PI:

- SSH to the Raspberry PIs

----
$ ssh pi@<PI_HOST>
PI $ cd WifiAnalyticsIoT/client/IoT-Analytics-Http
----

- Modify the file __client/IoT-Analytics-Http/src/main/resources/application.properties__ to connect to the right Spring XD server and to use the correct tshark command syntax.

- Start the client:

----
$ cd WifiAnalyticsIoT/client/IoT-Analytics-Http
$ ./gradlew run
----
 
- Do the above steps for each least 3 Raspberry PIs 
- Refresh the browser at http://<server>:8080/


