CREATE DATABASE IoTDemo;

CREATE TABLE IF NOT EXISTS PROBE_REQUESTS (
	PROBE_TIMESTAMP NUMERIC(10) NOT NULL,
	HOST VARCHAR(16) NOT NULL,
	DEVICE_ID VARCHAR(32) NOT NULL,
	SIGNAL_DBM INTEGER NOT NULL,
	PRIMARY KEY (PROBE_TIMESTAMP, HOST)
)